tasks:
  - init: |
      ./init.sh
      wget -L http://dl.opencellsoft.com/current/opencell.war -o opencell.war
      
      docker-compose pull
  - command: |
      docker-compose up


ports:

  - port: 8080
    onOpen: open-preview


vscode:
  extensions:
    - ms-azuretools.vscode-docker
