tasks:
  - name: Back-End
    init: |
      echo ">>> Downloading opencell softwares & docker images"
      mkdir input-files 
      wget -L http://dl.opencellsoft.com/current/opencell.war --output-document input-files/opencell.war
      wget -L http://dl.opencellsoft.com/current/import-postgres.sql  --output-document input-files/import-postgres.sql
      wget -L http://dl.opencellsoft.com/keycloak/init-user-db.sh  --output-document input-files/init-user-db.sh
      wget -L https://dl.opencellsoft.com/keycloak/opencell-realm-and-users.json  --output-document input-files/opencell.json
      echo "elasticsearch.restUri=" > input-files/opencell-admin.properties
      sudo chown  1000:1000  input-files/opencell-admin.properties
      echo "Pulling docker images from docker hub"
      docker-compose pull

    command: |
      echo -n "URL=" > .env
      echo  -n $(gp url 9090) >> .env
      echo "/auth" >> .env 
      mvn clean install
      docker-compose up

