version: '2.1'
services:

  postgres:
    image: postgres:alpine
    container_name: postgres-wildfly
    environment:
      POSTGRES_USER: opencell_db_user
      POSTGRES_PASSWORD: opencell_db_password
      POSTGRES_DB : opencell_db
      POSTGRES_PORT : 5432
    volumes:
       - ./input-files/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
       - ./input-files/import-postgres.sql:/docker-entrypoint-initdb.d/import-postgres.sql

  opencell:
    image: opencell/wildfly-opencell:11.0.0
    container_name: opencell
    depends_on:
      - postgres
    environment:
      KEYCLOAK_URL: https://8080-ryder05-dockercompose-ldat3qsoc62.ws-eu47.gitpod.io//auth
      PROXY_ADDRESS_FORWARDING: true
      WILDFLY_PROXY_ADDRESS_FORWARDING: true
    ports:
      - "8080:8080"
    volumes:
      - ./input-files/opencell.war:/opt/jboss/wildfly/standalone/deployments/opencell.war
      - ./input-files/opencell-admin.properties:/opt/jboss/wildfly/standalone/configuration/opencell-admin.properties
